out_dir: results
metric_best: ap
accelerator: "cuda:0"
mlflow:
  use: False
  project: Exp
  name: peptides-func-SpectralAttention
wandb:
  use: False
  project: peptides-func
dataset:
  format: OGB
  name: peptides-functional
  task: graph
  task_type: classification_multilabel
  transductive: False
  node_encoder: True
  node_encoder_name: Atom
  node_encoder_bn: False
  edge_encoder: True
  edge_encoder_name: Bond
  edge_encoder_bn: False
posenc_RRWP:
  enable: False
  ksteps: 17
  add_identity: True
  add_node_attr: False
train:
  mode: custom
  batch_size: 32
  eval_period: 1
  ckpt_period: 100
model:
  type: GritTransformer
  loss_fun: cross_entropy
  graph_pooling: mean
gt:
  layer_type: SpectralAttention
  layers: 3
  n_heads: 4
  dim_hidden: 128  # `gt.dim_hidden` must match `gnn.dim_inner`
  dropout: 0.1
  attn_dropout: 0.1
  layer_norm: False
  batch_norm: True
  attn:
    K: 3           # Chebyshev polynomial order
    full_attn: True
    edge_enhance: False
    O_e: False
    norm_e: False
    signed_sqrt: False
gnn:
  head: default
  layers_pre_mp: 0
  layers_post_mp: 1
  dim_inner: 128  # `gt.dim_hidden` must match `gnn.dim_inner`
  batchnorm: True
  act: relu
  dropout: 0.0
optim:
  clip_grad_norm: True
  optimizer: adamW
  weight_decay: 1e-5
  base_lr: 0.0005
  max_epoch: 100
  scheduler: cosine_with_warmup
  num_warmup_epochs: 10
loss:
  attention_improvement:
    enable: False
